apiVersion: apps/v1
kind: Deployment
#  These labels are attached to the Deployment resource itself. They provide metadata that can be used to identify, organize, or filter the deployment
metadata:
  name: user-management-deployment
  namespace: development
  labels:
    app: user-management-app
    env: development
    version: v1.0.2

#  These labels are used to select the set of pods that the deployment will manage
spec:
  selector:
    matchLabels:
      app: user-management-app
      env: development
      version: v1.0.2
  replicas: 2
  #  These labels are applied to the pods that are created by this deployment. Every time the deployment creates a new pod (due to scaling or updating), these labels are automatically assigned to the pod
  template:
    metadata:
      labels:
        app: user-management-app
        env: development
        version: v1.0.2

    spec:
      containers:
        - name: user-management-app
          image: ahmedgodaa/ats-user-management-service:v1.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MAIL_EMAIL
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: MAIL_EMAIL

            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: MAIL_PASSWORD

            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: user-management-config-map-v2
                  key: API_VERSION

