apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: development
spec:
  selector:
    app: user-management-app
    env: development
    version: v1.0.1
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort