apiVersion: v1
kind: Service
metadata:
  name: workspace-service-v2
  namespace: development
spec:
  selector:
    app: workspace-app
    env: development
    version: v1.0.1
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort