/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.AddMemberToWorkspaceEvent;
import org.openapitools.model.CreateWorkspaceEvent;
import org.openapitools.model.DeleteWorkspaceEvent;
import org.openapitools.model.RemoveMemberFromWorkspaceEvent;
import org.openapitools.model.StringMessageResponse;
import org.openapitools.model.UpdateWorkspaceEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-08-29T20:04:34.785275100+03:00[Africa/Cairo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "workspace-controller", description = "the workspace-controller API")
public interface WorkspaceApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /workspace/addMember
     *
     * @param addMemberToWorkspaceEvent  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "addMemberToWorkspace",
        tags = { "workspace-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "*/*", schema = @Schema(implementation = StringMessageResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/workspace/addMember",
        produces = { "*/*" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<StringMessageResponse> addMemberToWorkspace(
        @Parameter(name = "AddMemberToWorkspaceEvent", description = "", required = true) @Valid @RequestBody AddMemberToWorkspaceEvent addMemberToWorkspaceEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /workspace/create
     *
     * @param createWorkspaceEvent  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createWorkspace",
        tags = { "workspace-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "*/*", schema = @Schema(implementation = StringMessageResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/workspace/create",
        produces = { "*/*" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<StringMessageResponse> createWorkspace(
        @Parameter(name = "CreateWorkspaceEvent", description = "", required = true) @Valid @RequestBody CreateWorkspaceEvent createWorkspaceEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /workspace/delete
     *
     * @param deleteWorkspaceEvent  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteWorkspace",
        tags = { "workspace-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "*/*", schema = @Schema(implementation = StringMessageResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/workspace/delete",
        produces = { "*/*" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<StringMessageResponse> deleteWorkspace(
        @Parameter(name = "DeleteWorkspaceEvent", description = "", required = true) @Valid @RequestBody DeleteWorkspaceEvent deleteWorkspaceEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /workspace/removeMember
     *
     * @param removeMemberFromWorkspaceEvent  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "removeMemberFromWorkspace",
        tags = { "workspace-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "*/*", schema = @Schema(implementation = StringMessageResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/workspace/removeMember",
        produces = { "*/*" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<StringMessageResponse> removeMemberFromWorkspace(
        @Parameter(name = "RemoveMemberFromWorkspaceEvent", description = "", required = true) @Valid @RequestBody RemoveMemberFromWorkspaceEvent removeMemberFromWorkspaceEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /workspace/update
     *
     * @param updateWorkspaceEvent  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateWorkspace",
        tags = { "workspace-controller" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "*/*", schema = @Schema(implementation = StringMessageResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/workspace/update",
        produces = { "*/*" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<StringMessageResponse> updateWorkspace(
        @Parameter(name = "UpdateWorkspaceEvent", description = "", required = true) @Valid @RequestBody UpdateWorkspaceEvent updateWorkspaceEvent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "*/*", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
